ctf:
  enabled: false
  minPlayers: 2
  blueSpawn: 0, 50, 0
  redSpawn: 0, 50, 0
  neutralSpawn: 0, 50, 0
  capturePoints:
  - 60, 50, 0
  - 80, 50, 0
  - 100, 50, 0
  pointsBlue:
  - -1
  pointsRed:
  - -1
  blueWin:
  - 0
  - 1
  - 2
  redWin:
  - 0
  - 1
  - 2
  capturePer20Ticks: 0.2
  mode: conquer
  world: world
  useSiteBoard: false
  siteLocation: "http://localhost/capture-points/"
  siteKey: ""
  outfits:
  - name: Warrior
    description: A powerful tank with heavy armor
    potions:
    - effect: SLOW
    chestplate:
      material: iron_chestplate
      enchants:
      - 4, 2
      - 1, 1
    leggings:
      material: iron_leggings
    items:
    - name: Warrior's Sword
      material: diamond_sword
    - material: potion
      damage: 16421
      count: 3
    - material: golden_apple
      name: Apple of restoration
      count: 1
  - name: Archer
    chestplate:
      material: leather_chestplate
      color: 135, 111, 78
      enchants:
      - 4, 2
    leggings:
      material: leather_leggings
      color: 54, 50, 46
    boots:
      material: leather_boots
      color: 10, 10, 10
    items:
    - name: Archer's Sword
      material: iron_sword
    - name: Archer's Bow
      material: bow
      enchants:
      - 48, 1
    - name: Normal Arrow
      material: arrow
      count: 60
    - material: golden_apple
      name: Apple of restoration
      count: 2
  - name: Spy
    potions:
    - effect: SPEED
      amplifier: 0
    - effect: INVISIBILITY
      amplifier: 1
    - effect: NIGHT_VISION
    helmet: false
    teamLeather: true
    boots:
      name: Boots of Sneaking
      material: leather_boots
      enchants:
      - 7, 2
      - 34, 3
    items:
    - material: iron_sword
      name: Spy's Stabby Stabby Sword
      enchants:
      - 17, 2
    - name: Assassination Splash potion
      material: potion
      damage: 16388
      count: 2
    - name: Red Herring
      material: cooked_fish
      count: 4
