name: CaptureTheFlag
main: tamerial.ctf.CaptureTheFlag
version: 0.0
commands:
  start:
    permission: ctf.start
    description: Starts a round, regardless of how many players are online.
    usage: /<command>
  pause:
    permission: ctf.pause
    description: Pauses a game indefinitely
  gametime:
    permission: ctf.gametime
    description: Changes the time remaining in the game.
    usage: /<command> [time]
  listmodes:
    permission: ctf.listmodes
    description: Lists the possible modes for a game
  progress:
    permission: ctf.progress
    description: Progresses a capture point to a specific value
    usage: /<command> [id] [value]
  join:
    description: Join a team, as long as joining won't make your team more than one person overpowered
    usage: /<command> [red / blue]
    aliases: team  
  forcejoin:
    description: Makes a player join a team.
    usage: /<command> [player] [team]
    permission: ctf.forcejoin
  class:
    description: Selects a class
    aliases: be
  
permissions:
  ctf.gamemaster:
    default: op
    children:
      ctf.start: true
      ctf.pause: true
      ctf.listmodes: true
      ctf.gametime: true
      ctf.forcejoin: true
  ctf.start:
    default: op
  ctf.pause:
    default: op
  ctf.gametime:
    default: op
  ctf.forcejoin:
    default: op
  ctf.listmodes:
    default: op
  ctf.progress:
    default: op
    